Repository storybookjs/addon-designs, pull requests merged in 2023-08, with the labels that each got.

#207 Don't use key anymore for rendering addon
  packages/storybook-addon-designs/src/register/index.tsx
Labels: category: bug, patch

#205 Fix README badge URLs
  README.md
Labels: scope: docs

#210 Upgrade auto and add released plugin
  package-lock.json
  packages/storybook-addon-designs/package.json
Labels: skip-release, internal, dependencies
